In [1]:
import torch

In [12]:
tensor0d = torch.tensor(1)

tensor1d = torch.tensor([1,2,3])

tensor2d = torch.tensor([[1,2],[3,4]])

tensor3d = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])


print("0d tensor: \n", tensor0d, "\n")
print("1d tensor: \n", tensor1d, "\n")
print("2d tensor: \n", tensor2d, "\n")
print("3d tensor: \n", tensor3d, "\n")
print(tensor1d.dtype)

floatvec = torch.tensor([1.0, 2.0, 3.0])
print(floatvec.dtype)

floatvec = tensor1d.to(torch.float16)
print(floatvec.dtype)


0d tensor: 
 tensor(1) 

1d tensor: 
 tensor([1, 2, 3]) 

2d tensor: 
 tensor([[1, 2],
        [3, 4]]) 

3d tensor: 
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]) 

torch.int64
torch.float32
torch.float16
